/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IVelirionDAO } from "./IVelirionDAO";
export type { IVelirionNFT } from "./IVelirionNFT";
export type { IVelirionReferral } from "./IVelirionReferral";
export type { IVelirionStaking } from "./IVelirionStaking";
