/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { VelirionDAO } from "./VelirionDAO";
export type { VelirionTimelock } from "./VelirionTimelock";
export type { VelirionTreasury } from "./VelirionTreasury";
