/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { VelirionReferral__factory } from "./VelirionReferral__factory";
export { VelirionStaking__factory } from "./VelirionStaking__factory";
export { VelirionToken__factory } from "./VelirionToken__factory";
